version: '3.9'

services:
  mysql_service_blablabla:
    ##image: mysql:8
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=dockerdefinitivo
      - MYSQL_USER:=dockerdefinitivo
      - MYSQL_PASSWORD=dockerdefinitivo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  mysql_data:
    driver: local