version: '3.9'

services:
  postgres_service_blablabla:
    image: postgres:14
    environment:
      - POSTGRES_DB=dockerdefinitivo
      - POSTGRES_USER=dockerdefinitivo
      - POSTGRES_PASSWORD=dockerdefinitivo
      - TZ=GMT
    #ports:
    #  - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d
    networks:
      - db
  
  postgres_ui:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=fabiostefani@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 80:80
    networks:
      - db
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  db:
    driver: bridge