version: '3.9'

services:
  sqlserver_service_blablabla:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dock&rD&finitivo                  
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql/data
      #- ./scripts/:/docker-entrypoint-initdb.d
    networks:
      - db
  
volumes:
  sqlserver_data:
    driver: local

networks:
  db:
    driver: bridge